-- Add telemetry and hardware profile columns to user_devices
ALTER TABLE public.user_devices 
  ADD COLUMN IF NOT EXISTS pcb_revision TEXT,
  ADD COLUMN IF NOT EXISTS bootloader TEXT,
  ADD COLUMN IF NOT EXISTS flash_size BIGINT,
  ADD COLUMN IF NOT EXISTS free_flash BIGINT,
  ADD COLUMN IF NOT EXISTS ram BIGINT,
  ADD COLUMN IF NOT EXISTS free_ram BIGINT,
  ADD COLUMN IF NOT EXISTS chip_id TEXT,
  ADD COLUMN IF NOT EXISTS wifi_ssid TEXT,
  ADD COLUMN IF NOT EXISTS ip_address TEXT,
  ADD COLUMN IF NOT EXISTS timezone TEXT,
  ADD COLUMN IF NOT EXISTS uptime BIGINT,
  ADD COLUMN IF NOT EXISTS restart_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS installation_date TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS warranty_until TIMESTAMP WITH TIME ZONE;
